
#include <Arduino.h>
#include <ESP32WifiCLI.hpp>
#include <LightningSensor.h>
#include <PubSubClient.h>
#include <String.h>
#include <WiFi.h>
#include <WiFiClient.h>
#include <arduino-timer.h>
#include <StormFrontDistance.h>
#include <ArduinoJson.h>
#include <StreamUtils.h>
#include <DateTime.h>

// The calibration value for my board is 88 picoFarads.
const int TUNING_CAPACITOR_DEFAULT = 88;
const bool REPORT_DISTURBER_DEFAULT = false;
const char* HOSTNAME_DEFAULT = "bzzt";
const String SYSTEM_HOSTNAME(HOSTNAME_DEFAULT);
const char* TZ_AMERICA_CHICAGO = "CST6CDT,M3.2.0,M11.1.0";
// Plucked from /usr/share/i18n/locales/en_US on a local linux box
// % Appropriate date and time representation (%c)
// d_t_fmt "%a %d %b %Y %r %Z"
const char* DEFAULT_DATETIME_FORMAT = "%a %d %b %Y %r %Z";

// Cloud art under ISC License ripped from https://github.com/schachmat/wego/blob/bf192ea66e771a8031117845bfa04c603f903f41/frontends/ascii-art-table.go#L258
// BZZT block element ASCII Art generated by https://patorjk.com/software/taag/#p=display&f=ANSI%20Regular&t=BZZT
// Contains color control codes for any competent terminal program.
/*
     .-.        ██████  ███████ ███████ ████████
    (   ).      ██   ██    ███     ███     ██
   (___(__)     ██████    ███     ███      ██
  ‚ʻ⚡ʻ‚⚡‚ʻ    ██   ██  ███     ███       ██
  ‚ʻ‚ʻ⚡ʻ‚ʻ     ██████  ███████ ███████    ██
*/
const char logo[] =
"                                                                           \r\n"
"\033[38;5;244;1m     .-.     \033[0m   ██████  ███████ ███████ ████████\r\n"
"\033[38;5;244;1m    (   ).   \033[0m   ██   ██    ███     ███     ██\r\n"
"\033[38;5;244;1m   (___(__)  \033[0m   ██████    ███     ███      ██\r\n"
"\033[38;5;33;1m  ‚ʻ\033[38;5;228;5m⚡\033[38;5;33;25mʻ‚\033[38;5;228;5m⚡\033[38;5;33;25m‚ʻ   \033[0m ██   ██  ███     ███       ██\r\n"
"\033[38;5;33;1m  ‚ʻ‚ʻ\033[38;5;228;5m⚡\033[38;5;33;25mʻ‚ʻ   \033[0m  ██████  ███████ ███████    ██\r\n"
"                                                                           \r\n"
"\n"
"";

SensorSettings settings;
LightningSensor sensor;
WiFiClient wifiClient;
PubSubClient mqtt(wifiClient);

Timer<> timer = timer_create_default(); // create a timer with default settings

#pragma region "Error Visibility"
bool toggleErrorLed(void *)
{
  static bool state = false;

  state = !state;
  neopixelWrite(LED_BUILTIN, state ? RGB_BRIGHTNESS : 0, 0, 0);

  return true;
}

void setErrorStatus(bool isErrored = true)
{
  static Timer<>::Task error_task = 0;

  if (isErrored)
  {
    if (error_task == 0)
    {
      error_task = timer.every(500, toggleErrorLed);
    }
  }
  else
  {
    if (error_task != 0)
    {
      timer.cancel(error_task);
      error_task = 0;
    }
  }
}
#pragma endregion

#pragma region "MQTT Management"
bool checkSensor(void *)
{
  SensorEvent event;
  auto interrupted = sensor.getSensorEvent(&event);

  if (interrupted)
  {
    if (mqtt.connect(SYSTEM_HOSTNAME.c_str()))
    {
      StaticJsonDocument<256> doc;

      doc["type"] = statusToString(event.type);
      doc["distance"] = distanceToString(event.distance);
      doc["energy"] = event.energy;
      int64_t time_us = (int64_t)event.timestamp.tv_sec * 1000000L + (int64_t)event.timestamp.tv_usec;
      doc["timestamp"] = time_us;

      mqtt.beginPublish("lightning/event", measureJson(doc), false);
      BufferingPrint bufferedClient(mqtt, 32);
      serializeJson(doc, bufferedClient);
      bufferedClient.flush();
      mqtt.endPublish();
      setErrorStatus(false);
    }
    else
    {
      setErrorStatus(true);
    }
  }

  return true; // repeat? true
}

void onPubSubCallback(char *topic, byte *payload, unsigned int length)
{
  if (strcmp(topic, "lightning/ping") == 0)
  {
    StringPrint stream;
    stream.printf("Cores: %u\n", ESP.getChipCores());
    stream.printf("Model: %s\n", ESP.getChipModel());
    stream.printf("Revision: %u\n", ESP.getChipRevision());
    stream.printf("IP: %s\n", WiFi.localIP().toString().c_str());

    mqtt.publish("lightning/pong", stream.str().c_str(), false);
  }
}
#pragma endregion

#pragma region "Wifi CLI Callbacks"
class mESP32WifiCLICallbacks : public ESP32WifiCLICallbacks
{
    void onWifiStatus(bool isConnected)
    {
      if (isConnected)
      {
        if (!mqtt.connected())
        {

          String broker = wcli.getString("BROKER_HOST", "");
          if (!broker.isEmpty())
          {
            mqtt.setServer(broker.c_str(), 1883);
            mqtt.setCallback(onPubSubCallback);
          }

          if (mqtt.connect(SYSTEM_HOSTNAME.c_str()) && mqtt.subscribe("lightning/ping"))
          {
            setErrorStatus(false);
          }
          else
          {
            setErrorStatus(true);
          }
        }

        if (!DateTime.isTimeValid()) {
          DateTime.setTimeZone(TZ_AMERICA_CHICAGO);
          DateTime.begin();
        }

        neopixelWrite(LED_BUILTIN, 0, RGB_BRIGHTNESS, 0);
      }
      else
      {
        neopixelWrite(LED_BUILTIN, 0, 0, RGB_BRIGHTNESS);
      }
    }

    void onHelpShow()
    {

    }

    void onNewWifi(String ssid, String passw) { }
};

void reboot(char *args, Stream *response){
  wcli.shell->clear();
  wcli.client->stop();
  ESP.restart();
}

void setBroker(char *args, Stream *response)
{
  String argVal = wcli.parseArgument(args);

  argVal.trim();
  
  if (argVal.length() == 0) {
    response->println("Missing argument <BROKER_HOST>");
    return;
  }

  wcli.setString("BROKER_HOST", argVal);
  response->println("\r\nMQTT broker set to " + argVal);
  response->println("Please reboot to apply the change.");
}

void printCurrentDate(char *args, Stream *response) {
  if (DateTime.isTimeValid()) {
    String currentTime = DateTime.format(DEFAULT_DATETIME_FORMAT);
    response->printf("The system clock is valid.\n%s\n", currentTime.c_str());
  } else {
    response->println("The system clock is not valid.");
  }

}

void clearStorage(char *args, Stream *response) {
  wcli.clearSettings();
}

void setSetting(char *args, Stream *response) {
  Pair<String, String> operands = wcli.parseCommand(args);

  String argName = operands.first();

  if (argName.isEmpty()) {
    response->println("Missing argument <name>");

    response->println("\nValid Names:");
    response->println("\tsensorLocation");
    response->println("\ttuningCapacitor");
    response->println("\tlightningThreshold");
    response->println("\twatchdogThreshold");
    response->println("\tnoiseFloor");
    response->println("\tspikeRejection");
    response->println("\treportDisturber");

    return;
  }

  String argValue = operands.second();

  if (argName.equalsIgnoreCase("sensorLocation")) {
    if (argValue.isEmpty()) {
      response->println("Missing argument <value>");
      return;
    }

    if (argValue.equalsIgnoreCase("INDOOR")) {
      settings.sensorLocation = INDOOR;
    } else if (!argValue.equalsIgnoreCase("OUTDOOR")) {
      settings.sensorLocation = OUTDOOR;
    } else {
      response->println("Invalid argument <value>: You must enter either indoor or outdoor.");
      return;
    }

    SparkFun_AS3935 rawSensor = sensor.getSensor();
    rawSensor.setIndoorOutdoor(settings.sensorLocation);

    return;
  }

  if (argName.equalsIgnoreCase("tuningCapacitor")) {
    if (argValue.isEmpty()) {
      response->println("Missing argument <value>");
      return;
    }

    int value = argValue.toInt();
    if (value < 0 || value > 120) {
      response->println("Invalid argument <value>: You must enter a number between 0 and 120.");
      return;
    }

    if (value % 8 != 0) {
      response->println("Invalid argument <value>: You must enter a number divisible by 8.");
      return;
    }

    settings.tuningCapacitor = (uint8_t) value;

    SparkFun_AS3935 rawSensor = sensor.getSensor();
    rawSensor.tuneCap(settings.tuningCapacitor);

    return;
  }

  if (argName.equalsIgnoreCase("lightningThreshold")) {
    if (argValue.isEmpty()) {
      response->println("Missing argument <value>");
      return;
    }

    int value = argValue.toInt();
    if (value != 1 && value != 5 && value != 9 && value != 16) {
      response->println("Invalid argument <value>: You must enter 1, 5, 9, or 16.");
      return;
    }

    settings.lightningThreshold = (uint8_t) value;

    SparkFun_AS3935 rawSensor = sensor.getSensor();
    rawSensor.lightningThreshold(settings.lightningThreshold);

    return;
  }

  if (argName.equalsIgnoreCase("watchdogThreshold")) {
    if (argValue.isEmpty()) {
      response->println("Missing argument <value>");
      return;
    }

    int value = argValue.toInt();
    if (value < 0 || value > 10) {
      response->println("Invalid argument <value>: You must enter a number between 0 and 10.");
      return;
    }

    settings.watchdogThreshold = (uint8_t) value;

    SparkFun_AS3935 rawSensor = sensor.getSensor();
    rawSensor.watchdogThreshold(settings.watchdogThreshold);

    return;
  }

  if (argName.equalsIgnoreCase("noiseFloor")) {
    if (argValue.isEmpty()) {
      response->println("Missing argument <value>");
      return;
    }

    int value = argValue.toInt();
    if (value < 1 || value > 7) {
      response->println("Invalid argument <value>: You must enter a number between 1 and 7.");
      return;
    }

    settings.noiseFloor = (uint8_t) value;

    SparkFun_AS3935 rawSensor = sensor.getSensor();
    rawSensor.setNoiseLevel(settings.noiseFloor);

    return;
  }

  if (argName.equalsIgnoreCase("spikeRejection")) {
    if (argValue.isEmpty()) {
      response->println("Missing argument <value>");
      return;
    }

    int value = argValue.toInt();
    if (value < 1 || value > 11) {
      response->println("Invalid argument <value>: You must enter a number between 1 and 11.");
      return;
    }

    settings.spikeRejection = (uint8_t) value;

    SparkFun_AS3935 rawSensor = sensor.getSensor();
    rawSensor.spikeRejection(settings.spikeRejection);

    return;
  }

  if (argName.equalsIgnoreCase("reportDisturber") == 1) {
    if (argValue.isEmpty()) {
      response->println("Missing argument <value>");
      return;
    }

    int value = argValue.toInt();
    if (value < 0 || value > 1) {
      response->println("The value argument must be 1 or 0, indicating true or false respectively.");
      return;
    }

    settings.reportDisturber = (bool) value;

    SparkFun_AS3935 rawSensor = sensor.getSensor();
    rawSensor.maskDisturber(!settings.reportDisturber);

    return;
  }

  response->println("Setting name not recognized.");
}

void getSetting(char *args, Stream *response) {
  Pair<String, String> operands = wcli.parseCommand(args);
  
  String argName = operands.first();
  
  if (argName.isEmpty()) {
    response->println("Missing argument <name>");

    response->println("\nValid Names:");
    response->println("\tsensorLocation");
    response->println("\ttuningCapacitor");
    response->println("\tlightningThreshold");
    response->println("\twatchdogThreshold");
    response->println("\tnoiseFloor");
    response->println("\tspikeRejection");
    response->println("\treportDisturber");

    return;
  }

  String argValue = operands.second();

  if (argName.equalsIgnoreCase("sensorLocation")) {
    SparkFun_AS3935 rawSensor = sensor.getSensor();
    settings.sensorLocation = rawSensor.readIndoorOutdoor();

    switch (settings.sensorLocation)
    {
    case INDOOR:
      response->println("sensorLocation: INDOOR");
      break;
    case OUTDOOR:
      response->println("sensorLocation: OUTDOOR");
    default:
      response->printf("Invalid Setting! sensorLocation: %#x");
      break;
    }

    return;
  }

  if (argName.equalsIgnoreCase("tuningCapacitor")) {
    SparkFun_AS3935 rawSensor = sensor.getSensor();
    settings.tuningCapacitor = rawSensor.readTuneCap();

    response->printf("tuningCapacitor: %upF\n", settings.tuningCapacitor);

    return;
  }

  if (argName.equalsIgnoreCase("lightningThreshold")) {
    SparkFun_AS3935 rawSensor = sensor.getSensor();
    settings.lightningThreshold = rawSensor.readLightningThreshold();

    response->printf("lightningThreshold: %u\n", settings.lightningThreshold);

    return;
  }

  if (argName.equalsIgnoreCase("watchdogThreshold")) {
    SparkFun_AS3935 rawSensor = sensor.getSensor();
    settings.watchdogThreshold = rawSensor.readWatchdogThreshold();

    response->printf("watchdogThreshold: %u\n", settings.watchdogThreshold);

    return;
  }

  if (argName.equalsIgnoreCase("noiseFloor")) {
    SparkFun_AS3935 rawSensor = sensor.getSensor();
    settings.noiseFloor = rawSensor.readNoiseLevel();

    response->printf("noiseFloor: %u\n", settings.noiseFloor);

    return;
  }

  if (argName.equalsIgnoreCase("spikeRejection") == 1) {
    SparkFun_AS3935 rawSensor = sensor.getSensor();
    settings.spikeRejection = rawSensor.readSpikeRejection();

    response->printf("spikeRejection: %u\n", settings.spikeRejection);

    return;
  }

  if (argName.equalsIgnoreCase("reportDisturber") == 1) {
    SparkFun_AS3935 rawSensor = sensor.getSensor();

    settings.reportDisturber = !((bool) rawSensor.readMaskDisturber());

    response->printf("reportDisturber: %s\n", settings.reportDisturber ? "true" : "false");

    return;
  }

  response->println("Setting name not recognized.");
}

void displayOsc(char *args, Stream *response) {
  Pair<String, String> operands = wcli.parseCommand(args);
  
  String argValue = operands.first();

  if (argValue.isEmpty()) {
    response->println("Missing argument <value>");
    return;
  }

  int value = argValue.toInt();

  if (value < 0 || value > 1) {
    response->println("The value argument must be 1 or 0, indicating true or false respectively.");
    return;
  }

  String argOsc = operands.second();

  if (argOsc.isEmpty()) {
    response->println("Missing argument <osc>");
  }

  int osc = argOsc.toInt();

  if (osc < 1 || osc > 3) {
    response->println("The osc argument must be between 1 and 3");
  }

  if (value == 1) {
    sensor.detachInterruptPin();
  }

  SparkFun_AS3935 rawSensor = sensor.getSensor();
  rawSensor.displayOscillator((bool) value, osc);

  if (value == 0) {
    sensor.attachInterruptPin();
  }
}

#pragma endregion

void setup()
{
  neopixelWrite(LED_BUILTIN, 0, 0, 0);
  // Initialize serial and wait for port to open:
  Serial.begin(115200);

  // pinMode(BUTTON, INPUT);
  // pinMode(STATUS_LED, OUTPUT);

  WiFi.hostname(SYSTEM_HOSTNAME);

  Serial.flush(); // Only for showing the message on serial
  delay(1000);
  wcli.setCallback(new mESP32WifiCLICallbacks());

  // Enter your custom commands:
  wcli.add("broker", &setBroker, "\t<hostname> set the MQTT broker hostname");
  wcli.add("reboot", &reboot, "\tperform a ESP32 reboot");
  wcli.add("date", &printCurrentDate, "\t\tprint date and time from the system clock");
  wcli.add("clear", &clearStorage, "\t\tClear non-volatile storage.");
  wcli.add("set", &setSetting, "\t\t<name> <value> Set lightning sensor setting.");
  wcli.add("get", &getSetting, "\t\t<name> Get lightning sensor setting.");
  wcli.add("displayOsc", &displayOsc, "\t<value> <osc>");

  wcli.shell->clear();
  // Connect to WPA/WPA2 network
  wcli.shell->attachLogo(logo);
  wcli.begin();
  if (wcli.isTelnetRunning()) wcli.shellTelnet->attachLogo(logo);

  /*
    https://learn.adafruit.com/adafruit-esp32-feather-v2/pinouts#stemma-qt-connector-3112257

    At the top-left corner of the ESP32 module, is a STEMMA QT connector, labeled QT I2C on the silk.
    This connector allows you to connect a variety of sensors and breakouts with STEMMA QT connectors using various associated cables.

    You must enable the NEOPIXEL_I2C_POWER pin (GPIO 2) for the STEMMA QT connector power to work. Set it to be an output and HIGH in your code.

    There is a NEOPIXEL_I2C_POWER (GPIO 2) pin that must be set to an output and HIGH for the STEMMA QT connector power to work.
    For running in low power mode, you can disable (set output and LOW) the NEOPIXEL_I2C_POWER pin,
    this will turn off the separate 3.3V regulator that powers the QT connector's red wire
  */

  settings.tuningCapacitor = TUNING_CAPACITOR_DEFAULT;
  settings.reportDisturber = REPORT_DISTURBER_DEFAULT;

  if (!sensor.begin(settings)) {
    setErrorStatus(true);
  }

  // call the checkSensor function every 500 millis (0.5 second)
  // There is a one second window of time to read the interrupt register
  // after lightning is detected, and 1.5 after a disturber.
  timer.every(500, checkSensor);
}

void loop()
{
  mqtt.loop();
  timer.tick();
  wcli.loop();
}
